#!/usr/bin/env python3
"""Shared path constants for archived pre-GraphPilot FastVLM artifacts."""

from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
LEGACY_FASTVLM_ARTIFACT_ROOT = REPO_ROOT / "artifacts" / "legacy_fastvlm"
LEGACY_ANALYSIS_ROOT = LEGACY_FASTVLM_ARTIFACT_ROOT / "analysis"
LEGACY_AUX_EXPERIMENTS_ROOT = LEGACY_FASTVLM_ARTIFACT_ROOT / "aux_experiments"
LEGACY_CASES_BENCHMARK_ROOT = LEGACY_FASTVLM_ARTIFACT_ROOT / "cases_benchmark"
LEGACY_COCO_EVAL_ROOT = LEGACY_FASTVLM_ARTIFACT_ROOT / "coco_eval"
LEGACY_GQA_EVAL_ROOT = LEGACY_FASTVLM_ARTIFACT_ROOT / "gqa_eval"
LEGACY_GRAPH_INSPECT_ROOT = LEGACY_FASTVLM_ARTIFACT_ROOT / "graph_inspect"
LEGACY_GRAPH_INSPECT_AUXMASKROPE_RUNTIME_ROOT = (
    LEGACY_FASTVLM_ARTIFACT_ROOT / "graph_inspect_auxmaskrope_runtime"
)
LEGACY_HOST_EDGE_DIFF_ROOT = LEGACY_FASTVLM_ARTIFACT_ROOT / "host_edge_diff"
LEGACY_LOCAL_QAIRT_REPO_ROOT = LEGACY_FASTVLM_ARTIFACT_ROOT / "local_qairt_repo"
LEGACY_LOG_ROOT = LEGACY_FASTVLM_ARTIFACT_ROOT / "logs"
LEGACY_PARTITION_PLAN_ROOT = LEGACY_FASTVLM_ARTIFACT_ROOT / "partition_plans"
LEGACY_PREFILL_EXPERIMENTS_ROOT = LEGACY_FASTVLM_ARTIFACT_ROOT / "prefill_experiments"
LEGACY_REGENERATION_ROOT = LEGACY_FASTVLM_ARTIFACT_ROOT / "regeneration"
LEGACY_TMP_ROOT = LEGACY_FASTVLM_ARTIFACT_ROOT / "tmp"

